name: Build CFML wheels on Windows

on:
  push:
    branches: [ common_wheel ]

jobs:
  create-Windows:
    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.7']
        os: [ windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v2
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true


      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: cmake mingw-w64-x86_64-toolchain
          update: true
          path-type: inherit

      - name: Build CFML
        shell: msys2 {0}
        id: build
        run: |
          C:\\Miniconda\\condabin\\conda.bat activate test
          which python
          python -V
          pip install delvewheel
          pip wheel ./ --no-deps -w ./old/
          delvewheel show ./old/*.whl
          delvewheel repair --no-mangle-all -w dist -v ./old/*.whl
        env:
          MINGW_ARCH: MINGW64

      - uses: actions/upload-artifact@v2
        with:
          name: CrysFML - Windows
          path: ./dist/*.whl

  Upload_Artifacts:
    runs-on: windows-latest
    needs: [create-Windows]
    steps:
    - uses: actions/download-artifact@v2
    - name: What is downloaded
      run: |
        ls -al
    - name: Upload Artifacts GitHub releases
      uses: ncipollo/release-action@v1
      with:
        draft: false
        prerelease: true
        allowUpdates: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "./**/*.whl"
        tag: "CurrentBuild"
        body: "This is a Windows build of the CFML_api library."
